name: Node.js Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: install dependencies
        working-directory: ./app
        run: npm install
      - name: build electron apps
        working-directory: ./app
        run: npm run app:dir
        jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: install dependencies
        working-directory: ./app
        run: npm install
      - name: build electron apps
        working-directory: ./app
        run: npm run app:dir
      - uses: coactions/setup-xvfb@v1
        working-directory: ./app
        run: npx wdio run wdio.conf.js
